#Open API Specification

openapi: 3.0.0
info:
  title: SWAPI Serverless Node.js
  description: API Restful usando Serverless Framework
  contact:
    email: vict.benavente@gmail.com
  version: 1.0.11
servers:
  - url: https://ch5zkx5skh.execute-api.us-east-2.amazonaws.com/
    description: SWAPI Serverless Node.js

# components
components:
  schemas:
    ResponsePeople:
      type : object
      required:
      - nombre
      - color_cabello
      - nacimiento
      - masa
      - lugar_nacimiento
      - altura
      - fecha_de_creacion
      - url
      - fecha_actualizacion
      - color_piel
      - id
      - color_ojos
      - genero
      - peliculas
      - especies
      - vehiculos
      - naves
      properties:
        nombre:
          type: string
        color_cabello:
          type: string
        nacimiento:
          type: string
        masa:
          type: string
        lugar_nacimiento:
          type: string
        altura:
          type: string
        fecha_de_creacion:
          type: string
        url:
          type: string
        fecha_actualizacion:
          type: string
        color_piel:
          type: string
        color_ojos:
          type: string
        genero:
          type: string
        peliculas:
          type: array
        especies:
          type: array
        vehiculos:
          type: array
        naves:
          type: array
  
    ResponseStarship:
      type : object
      required:
      - nombre
      - modelo
      - manufactura
      - costo_en_creditos
      - longitud
      - velocidad_atmosferica_maxima
      - fecha_de_creacion
      - url
      - fecha_actualizacion
      - tripulacion
      - id
      - pasajeros
      - capacidad_de_carga
      - consumibles
      - hiperimpulsor_calificacion
      - mglt
      - clase
      - pilotos
      - peliculas
      properties:
        nombre:
          type: string
        modelo:
          type: string
        manufactura:
          type: string
        costo_en_creditos:
          type: string
        longitud:
          type: string
        velocidad_atmosferica_maxima:
          type: string
        fecha_de_creacion:
          type: string
        url:
          type: string
        fecha_actualizacion:
          type: string
        tripulacion:
          type: string
        id:
          type: string
        pasajeros:
          type: string
        capacidad_de_carga:
          type: string
        consumibles:
          type: string
        hiperimpulsor_calificacion:
          type: string
        mglt:
          type: string
        clase:
          type: string
        pilotos:
          type: array
        peliculas:
          type: array

    ResponseSpecie:
      type : object
      required:
      - id
      - fecha_de_creacion
      - url
      - fecha_actualizacion
      - nombre
      - clasificacion
      - designacion
      - altura
      - color_de_piel
      - color_de_cabello
      - color_de_ojos
      - esperanza_de_vida
      - lugar_nacimiento
      - lenguaje
      - personas
      - peliculas

      properties:
        id:
          type: string
        fecha_de_creacion:
          type: string
        url:
          type: string
        fecha_actualizacion:
          type: string
        nombre:
          type: string
        clasificacion:
          type: string
        designacion:
          type: string
        altura:
          type: string
        color_de_piel:
          type: string
        color_de_cabello:
          type: string
        color_de_ojos:
          type: string
        esperanza_de_vida:
          type: string
        lugar_nacimiento:
          type: string
        lenguaje:
          type: string
        personas:
          type: array
        peliculas:
          type: array

    ErrorNotFound:
      type: object
      description: Error Resource not found
      required:
      - message
      - status
      properties:
        message:
          default: "not found"
        status:
          default: 404

paths:
#personas
  /personas:
    get:
      tags:
        - "Personas"
      summary: Retorna una lista de personas

      responses:
        "200":
          description: "succesful operation"
          content:
            application/json:
              schema:
                type: object
                required:
                - personas
                properties:
                  data:
                    type: array
                    description: Array de personas
                    items:
                      $ref: '#/components/schemas/ResponsePeople'
        "404":
          description: "not found"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorNotFound'

    post:
      tags:
        - "Personas"
      summary: Crear nueva persona
      requestBody:
        description: Nueva persona a ser creada
        required: true
        content:
          application/json:
            schema:
              required:
              - nombre
              - color_cabello
              - nacimiento
              - masa
              - lugar_nacimiento
              - altura
              - color_piel
              - id
              - color_ojos
              - genero
              - peliculas
              - especies
              - vehiculos
              - naves
              properties:
                nombre:
                  type: string
                color_cabello:
                  type: string
                nacimiento:
                  type: string
                masa:
                  type: string
                lugar_nacimiento:
                  type: string
                altura:
                  type: string
                color_piel:
                  type: string
                id:
                  type: string
                color_ojos:
                  type: string
                genero:
                  type: string
                peliculas:
                  type: array
                especies:
                  type: array
                vehiculos:
                  type: array
                naves:
                  type: array
      responses:
         "200":
          description: "succesfull operation"
          content:
            application/json:
              schema:
                type: object
                required:
                - nave
                properties:
                  data:
                    $ref: '#/components/schemas/ResponsePeople'

  /personas/{id}:
    get:
      tags:
        - "Personas"
      summary: Retorna una persona

      parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
        description: identificador alfanumerico

      responses:
        "200":
          description: "succesful operation"
          content:
            application/json:
              schema:
                type: object
                required:
                - persona
                properties:
                  data:
                    $ref: '#/components/schemas/ResponsePeople'
        "404":
          description: "not found"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorNotFound'
   
# naves
  /naves:
    get:
      tags:
        - "Naves"
      summary: Retorna una lista de naves

      responses:
        "200":
          description: "succesful operation"
          content:
            application/json:
              schema:
                type: object
                required:
                - naves
                properties:
                  data:
                    type: array
                    description: Array de naves
                    items:
                      $ref: '#/components/schemas/ResponseStarship'
        "404":
          description: "not found"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorNotFound'

    post:
      tags:
        - "Naves"
      summary: Crear nueva nave
      requestBody:
        description: Nueva nave a ser creada
        required: true
        content:
          application/json:
            schema:
              required:
              - nombre
              - modelo
              - manufactura
              - costo_en_creditos
              - longitud
              - velocidad_atmosferica_maxima
              - tripulacion
              - pasajeros
              - capacidad_de_carga
              - consumibles
              - hiperimpulsor_calificacion
              - mglt
              - clase
              - pilotos
              - peliculas
              properties:
                nombre:
                  type: string
                modelo:
                  type: string
                manufactura:
                  type: string
                costo_en_creditos:
                  type: string
                longitud:
                  type: string
                velocidad_atmosferica_maxima:
                  type: string
                tripulacion:
                  type: string
                pasajeros:
                  type: string
                capacidad_de_carga:
                  type: string
                consumibles:
                  type: string
                hiperimpulsor_calificacion:
                  type: string
                mglt:
                  type: string
                clase:
                  type: string
                pilotos:
                  type: array
                peliculas:
                  type: array
      responses:
         "200":
          description: "succesfull operation"
          content:
            application/json:
              schema:
                type: object
                required:
                - data
                properties:
                  data:
                    $ref: '#/components/schemas/ResponseStarship'

  /naves/{id}:
    get:
      tags:
        - "Naves"
      summary: Retorna una nave
      parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
        description: identificador alfanumerico

      responses:
        "200":
          description: "succesful operation"
          content:
            application/json:
              schema:
                type: object
                required:
                - nave
                properties:
                  data:
                    $ref: '#/components/schemas/ResponseStarship'
        "404":
          description: "not found"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorNotFound'

# especies
  /especies:
    get:
      tags:
        - "Especies"
      summary: Retorna una lista de especies

      responses:
        "200":
          description: "succesful operation"
          content:
            application/json:
              schema:
                type: object
                required:
                - especies
                properties:
                  data:
                    type: array
                    description: Array de especies
                    items:
                      $ref: '#/components/schemas/ResponseSpecie'
        "404":
          description: "not found"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorNotFound'

    post:
      tags:
        - "Especies"
      summary: Crear nueva especie
      requestBody:
        description: Nueva especie a ser creada
        required: true
        content:
          application/json:
            schema:
              required:
              - nombre
              - clasificacion
              - designacion
              - altura
              - color_de_piel
              - color_de_cabello
              - color_de_ojos
              - esperanza_de_vida
              - lugar_nacimiento
              - lenguaje
              - personas
              - peliculas
              properties:
                nombre:
                  type: string
                clasificacion:
                  type: string
                designacion:
                  type: string
                altura:
                  type: string
                color_de_piel:
                  type: string
                color_de_cabello:
                  type: string
                color_de_ojos:
                  type: string
                esperanza_de_vida:
                  type: string
                lugar_nacimiento:
                  type: string
                lenguaje:
                  type: string
                personas:
                  type: array
                peliculas:
                  type: array
      responses:
         "200":
          description: "succesfull operation"
          content:
            application/json:
              schema:
                type: object
                required:
                - data
                properties:
                  data:
                    $ref: '#/components/schemas/ResponseSpecie'

  /especies/{id}:
    get:
      tags:
        - "Especies"
      summary: Retorna una especie
      parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
        description: identificador alfanumerico

      responses:
        "200":
          description: "succesful operation"
          content:
            application/json:
              schema:
                type: object
                required:
                - especie
                properties:
                  data:
                    $ref: '#/components/schemas/ResponseSpecie'
        "404":
          description: "not found"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorNotFound'
   