service: indra-serverless-challenge
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-2
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - arn:aws:dynamodb:us-east-2:020503494232:table/Especies
        - arn:aws:dynamodb:us-east-2:020503494232:table/Naves
        - arn:aws:dynamodb:us-east-2:020503494232:table/Peliculas
        - arn:aws:dynamodb:us-east-2:020503494232:table/Personas
        - arn:aws:dynamodb:us-east-2:020503494232:table/Vehiculos

functions:
  hello:
    handler: src/status.status
    events:
      - httpApi:
          path: /
          method: get
  addPeople:
    handler: src/services/people/add-people.addPeople
    events:
      - httpApi:
          path: /personas
          method: post
  getAllPeople:
    handler: src/services/people/get-all-people.getAllPeople
    events:
      - httpApi:
          path: /personas
          method: get
  getPeople:
    handler: src/services/people/get-people.getPeople
    events:
      - httpApi:
          path: /personas/{id}
          method: get   
  addStarship:
    handler: src/services/starships/add-starship.addStarship
    events:
      - httpApi:
          path: /naves
          method: post
  getAllStarships:
    handler: src/services/starships/get-all-starships.getAllStarships
    events:
      - httpApi:
          path: /naves
          method: get
  getStarship:
    handler: src/services/starships/get-starship.getStarship
    events:
      - httpApi:
          path: /naves/{id}
          method: get   

resources:
  Resources:
    Personas:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Personas
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
    Peliculas:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Peliculas
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
    Especies:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Especies
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
    Naves:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Naves
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
    Vehiculos:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Vehiculos
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH