service: indra-serverless-challenge
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-2

functions:
  hello:
    handler: src/hello.hello
    events:
      - httpApi:
          path: /
          method: get

resources:
  Resources:
    Personas:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Personas
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
    Peliculas:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Peliculas
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
    Especies:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Especies
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
    Naves:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Naves
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
    Vehiculos:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Vehiculos
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH